name: celebrating_bharath
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons for iOS-style icons
  cupertino_icons: ^1.0.8

  # For handling SVG files
  flutter_svg: ^2.1.0
  path_parsing: ^1.1.0
  path_drawing: ^1.0.1
  video_player: ^2.9.5
  cloudinary_flutter: ^1.3.0
  riverpod: ^2.0.0
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/my1.svg   # Old map with state IDs
    - assets/mp.svg  
    - assets/splash_logo.png
